name: Relatório de Bug
description: Crie um relatório de algo que não funciona corretamente
title: "Bug Report <insira um título para o bug>"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Este é um repositório de código aberto promovido pela Fatec Franca Dr. Thomaz Novelino. Sua contribuição é importante para melhorar nossa comunidade Fatec. 

        * Para perguntas, acesse [Fale conosco](https://site.fatecfranca.edu.br/a-fatec-franca/fale-conosco).
        * Antes de abrir uma issue, consulte a documentação.
        * Verifique se o problema já foi reportado [aqui](https://github.com/Leonardo-henriqu2/PI---5-v2/issues).
        * Caso o bug aparente apresentar potenciais perigos ao ser exposto ao público, não o publique, siga as instruções dispostas em nossas [políticas de segurança](https://github.com/Leonardo-henriqu2/PI---5-v2/blob/main/SECURITY.md).

  - type: textarea
    attributes:
      label: Descreva o bug
      description: Adicione uma descrição clara e concisa do que é o bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Como reproduzir
      description: Descreva os passos para reproduzir o comportamento, como por exemplo:
        - Vá para '...'
        - Clique em '...'
        - Role para baixo até '...'
        - Veja o erro
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comportamento esperado
      description: Adicione uma descrição clara do que você esperava que acontecesse.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Dispositivo utilizado
      description: Informe o aparelho, sistema operacional e versão onde ocorreu o bug. Exemplo:
        - **Desktop:**
          - SO: [ex. Windows, macOS]
          - Navegador: [ex. Chrome, Safari]
          - Versão: [ex. 22]
  
        - **Smartphone:**
          - Dispositivo: [ex. iPhone6]
          - SO: [ex. iOS8.1]
          - Navegador: [ex. navegador padrão, Safari]
          - Versão: [ex. 22]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Contexto adicional
      description: Adicione qualquer outro contexto sobre o problema que você achar necessário.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Este template foi inspirado nos padrões do GitHub.
